version: "3.9"
services:
   # MariaDB Service
    mariadb:
        image: mariadb:10.9
        environment:
            MYSQL_ROOT_PASSWORD: your_password
        networks:
          - npm
        volumes:
            - mysqldata:/var/lib/mysql

    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
          - 8745:80
        environment:
          - PMA_HOST: mariadb
        networks:
          - npm
        depends_on:
          - mariadb
    node-red:
        image: nodered/node-red:latest
        enviroment: 
          - TZ=America/Chicago 
        ports:
          - 2534:1880
        networks:
          - npm 
        volumes:
          - node-red-data:/data
        depends_on:
          - mariadb
    streamlit_board:
        image: streamlit:3-10-slim
        networks:
          - npm
        ports:
          - 8501:8501
        depends_on:
          - node-red
          - mariadb
  

# Volumes
volumes:
  mysqldata:

  node-red-data: